import { IntelligenceDomain, SourceTier } from '@panopticon/core/types'
import type { DataSourceConfig, SourceHealthState } from '@panopticon/core/types'
import { SourceStatus } from '@panopticon/core/types'

export const DATA_SOURCES: Record<string, DataSourceConfig> = {
  'usgs-earthquakes': {
    id: 'usgs-earthquakes',
    name: 'USGS Real-Time Earthquake Feed',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.CLIMATE,
    baseUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson',
    refreshIntervalMs: 60000, // 60s
    requiresAuth: false,
    authType: 'none',
    format: 'geojson',
    description: 'Provides real-time earthquake monitoring, magnitude levels, depths, and location details globally.',
    attribution: 'U.S. Geological Survey (USGS)',
    phase: 1,
  },
  'open-meteo': {
    id: 'open-meteo',
    name: 'Open-Meteo Global Forecast',
    tier: SourceTier.SPECIALIZED,
    domain: IntelligenceDomain.CLIMATE,
    baseUrl: 'https://api.open-meteo.com/v1/forecast',
    refreshIntervalMs: 300000, // 5 min
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'High-resolution atmospheric models delivering real-time weather overlay feeds.',
    attribution: 'Open-Meteo',
    phase: 1,
  },
  'noaa-swpc': {
    id: 'noaa-swpc',
    name: 'NOAA Space Weather Prediction',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.SPACE,
    baseUrl: 'https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json',
    refreshIntervalMs: 120000, // 120s
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'Real-time planetary K-index, geomagnetic storm alerts, and solar wind measurements.',
    attribution: 'NOAA Space Weather Prediction Center (SWPC)',
    phase: 1,
  },
  'gdelt': {
    id: 'gdelt',
    name: 'GDELT Global Event Registry',
    tier: SourceTier.RESEARCH,
    domain: IntelligenceDomain.GEOPOLITICAL,
    baseUrl: 'https://api.gdeltproject.org/api/v2/geo/geo',
    refreshIntervalMs: 900000, // 15 min
    requiresAuth: false,
    authType: 'none',
    format: 'geojson',
    description: 'Real-time mapping of global events, conflict scale, and social unrest mentions.',
    attribution: 'The GDELT Project',
    phase: 1,
  },
  'opensky-aviation': {
    id: 'opensky-aviation',
    name: 'OpenSky Network State Vectors',
    tier: SourceTier.RESEARCH,
    domain: IntelligenceDomain.AVIATION,
    baseUrl: 'https://opensky-network.org/api/states/all',
    refreshIntervalMs: 20000,
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'Live ADS-B and Mode S aircraft state vectors with optional authenticated rate limits.',
    attribution: 'OpenSky Network',
    phase: 2,
  },
  'nasa-firms': {
    id: 'nasa-firms',
    name: 'NASA FIRMS Active Fire Detections',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.CLIMATE,
    baseUrl: 'https://firms.modaps.eosdis.nasa.gov/api/area/csv',
    refreshIntervalMs: 600000,
    requiresAuth: true,
    authType: 'api-key',
    format: 'csv',
    description: 'Satellite thermal anomaly detections for active wildfires and heat events.',
    attribution: 'NASA FIRMS',
    phase: 2,
  },
  'gdacs-disasters': {
    id: 'gdacs-disasters',
    name: 'GDACS Global Disaster Alerts',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.CLIMATE,
    baseUrl: 'https://www.gdacs.org/xml/rss.xml',
    refreshIntervalMs: 300000,
    requiresAuth: false,
    authType: 'none',
    format: 'rss',
    description: 'Official multi-hazard disaster alerts, including earthquakes, tropical cyclones, floods, and volcanic events.',
    attribution: 'Global Disaster Alert and Coordination System (GDACS)',
    phase: 4,
  },
  'noaa-alerts': {
    id: 'noaa-alerts',
    name: 'NOAA/NWS Weather Alerts',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.CLIMATE,
    baseUrl: 'https://api.weather.gov/alerts/active',
    refreshIntervalMs: 120000,
    requiresAuth: false,
    authType: 'none',
    format: 'geojson',
    description: 'Active severe weather warning polygons and alert cells for the United States.',
    attribution: 'NOAA National Weather Service',
    phase: 4,
  },
  'eonet-events': {
    id: 'eonet-events',
    name: 'NASA EONET Natural Events',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.CLIMATE,
    baseUrl: 'https://eonet.gsfc.nasa.gov/api/v3/events',
    refreshIntervalMs: 900000,
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'NASA-curated natural event records for wildfires, storms, volcanoes, dust, floods, and sea/lake ice.',
    attribution: 'NASA Earth Observatory Natural Event Tracker (EONET)',
    phase: 4,
  },
  'noaa-swpc-alerts': {
    id: 'noaa-swpc-alerts',
    name: 'NOAA SWPC Alerts, Watches and Warnings',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.SPACE,
    baseUrl: 'https://services.swpc.noaa.gov/products/alerts.json',
    refreshIntervalMs: 120000,
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'Operational space-weather alerts, watches, and warnings.',
    attribution: 'NOAA Space Weather Prediction Center (SWPC)',
    phase: 4,
  },
  'celestrak-gp': {
    id: 'celestrak-gp',
    name: 'CelesTrak GP Orbital Elements',
    tier: SourceTier.SPECIALIZED,
    domain: IntelligenceDomain.SPACE,
    baseUrl: 'https://celestrak.org/NORAD/elements/gp.php',
    refreshIntervalMs: 3600000,
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'Authoritative public general perturbations orbital element sets for tracked satellite groups.',
    attribution: 'CelesTrak',
    phase: 4,
  },
  'who-don': {
    id: 'who-don',
    name: 'WHO Disease Outbreak News',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.HEALTH,
    baseUrl: 'https://www.who.int/feeds/entity/csr/don/en/rss.xml',
    refreshIntervalMs: 1800000,
    requiresAuth: false,
    authType: 'none',
    format: 'rss',
    description: 'Official disease outbreak notices and public health emergency updates.',
    attribution: 'World Health Organization',
    phase: 4,
  },
  'reliefweb-disasters': {
    id: 'reliefweb-disasters',
    name: 'ReliefWeb Disasters API',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.HUMANITARIAN,
    baseUrl: 'https://api.reliefweb.int/v1/disasters',
    refreshIntervalMs: 900000,
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'Humanitarian disaster records and situation metadata from UN OCHA ReliefWeb.',
    attribution: 'UN OCHA ReliefWeb',
    phase: 4,
  },
  'ukmto-warnings': {
    id: 'ukmto-warnings',
    name: 'UKMTO Maritime Security Warnings',
    tier: SourceTier.GOVERNMENT,
    domain: IntelligenceDomain.MARITIME,
    baseUrl: 'https://www.ukmto.org/indian-ocean/recent-incidents',
    refreshIntervalMs: 600000,
    requiresAuth: false,
    authType: 'none',
    format: 'json',
    description: 'Official maritime security incident notices for high-risk waters.',
    attribution: 'United Kingdom Maritime Trade Operations',
    phase: 4,
  },
}

/** Helper to generate initial health states for all active sources */
export function getInitialHealthStates(): Record<string, SourceHealthState> {
  const states: Record<string, SourceHealthState> = {}
  Object.keys(DATA_SOURCES).forEach((id) => {
    states[id] = {
      sourceId: id,
      status: SourceStatus.UNKNOWN,
      lastSuccessAt: null,
      lastErrorAt: null,
      lastError: null,
      consecutiveFailures: 0,
      avgResponseMs: 0,
      dataFreshnessMs: 0,
    }
  })
  return states
}
